Support php8.3 & github actions
Crujera27/install-ioncube-ubntu-php7.4 pull request #2
Opened 2024-10-09 15:50 UTC by zaibiti

This update introduces support for PHP 8.3 in the Bash script designed for installing IonCube Loader. Key modifications include:

    PHP 8.3 Support: A new option was added to the script for selecting PHP 8.3, along with the corresponding logic to handle installation.

    GitHub Actions Workflow: A GitHub Actions workflow was created to automate the execution of the updated script. This includes:
        Triggering the workflow manually via the GitHub UI.
        Setting up the environment using the latest Ubuntu runner.
        Installing PHP 8.3 and required extensions.
        Executing the IonCube Loader installation script.

Overall, these updates enhance the flexibility of the script and enable automated installation through GitHub Actions, making it easier for users to set up IonCube Loader with PHP 8.3.

2024-10-09 16:08 UTC, Crujera27 requested changes
Don't really understand the comments on the GitHub actions file. I prefer them to be removed to look cleaner. Overall seems okay, just remove the comments, and I'll merge this with no problem. Thanks for your contribution!

2024-10-10 15:13 UTC, zaibiti commented
I'll check that

2024-10-10 15:17 UTC, zaibiti commented
Done, it you want me to change anything else let me know

2024-10-10 18:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Crujera27/install-ioncube-ubuntu?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Crujera27/install-ioncube-ubuntu?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Crujera27/install-ioncube-ubuntu?pullRequest=2) it.</sub>

2024-10-10 18:21 UTC, Crujera27 commented
Seems fine, just if you want to continue, you'll have to sign the CLA. Just to prevent problems in the future with this small project.

2024-10-10 18:24 UTC, zaibiti commented
No problem, its now done

2024-10-10 19:46 UTC, Crujera27 approved these changes

2024-10-10 19:47 UTC, merged

2024-10-10 19:47 UTC, Crujera27 commented
Merged, thanks for your contribution!